<h1><a href="http://www.optimalbrowser.com/">Optimal</a></h1>
<h3>An OPML Browser</h3>
<!--
	By Dan MacTough - www.yabfog.com
-->
<h4><a href="http://www.yabfog.com/wp/optimal/" title="About Optimal">About Optimal</a> - 
<a href="http://www.optimalbrowser.com/widgetwiz.php" title="Optimal Widget Generator">Optimal Widget Generator</a> <span style="color: red; font-weight: bold">*NEW*</span> - 
<a href="http://www.yabfog.com/wp/optimal/#download" title="Download Optimal">Download Optimal</a> - 
<a href="javascript:location.href='http://www.optimalbrowser.com/?url='+location.href" alt="Open in Optimal Bookmarklet" title="Open in Optimal Bookmarklet">Open in Optimal Bookmarklet</a></h4>
